# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a08efe9fcd01933c4853e59a24cf1617d84111521f8b6a026af4fb5f0c77819922fe060ca0a09c1f7f8b82a13853d4a535bbcdb761c21747fab685071f56ef

test:
  secret_key_base: df99a36b97e85c96b2bb1ad19d695e183e3afc9013b0ba12791304d5102837f77a95af183fd0224d4a85e77e8b495b48493d4d52adc05fb221653775b6e2c208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
